import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next-app with Tailwind Styling",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-yellow-200`}>
        <nav className="bg-red-300 p-10 text-fuchsia-900 text-2xl flex justify-between">
        <Link href="/" className="p-2 font-bold  hover:text-fuchsia-500">Home</Link>
        <Link href="/categories" className="p-2 font-bold  hover:text-fuchsia-500 ">Categories</Link>
        <Link href="/bloggers" className="p-2 font-bold  hover:text-fuchsia-500 ">Bloggers</Link>
        <Link href="/submit-blog" className="p-2 font-bold  hover:text-fuchsia-500">Submit Blog</Link>
        <Link href="/settings" className="p-2 font-bold  hover:text-fuchsia-500 ">Settings</Link>
        <Link href="/support" className="p-2 font-bold  hover:text-fuchsia-500 ">Contact Support</Link>
        <Link href="/sign-up" className="p-2 font-bold  hover:text-fuchsia-500 ">Sign up</Link>
        </nav>
        {children}
        <footer className="bg-red-200 p-10 font-bold text-fuchsia-950 text-balance text-xl">Footer Note</footer>
        </body>
        
    </html>
  );
}
