// Import necessary modules for metadata, fonts, CSS, and Navbar component.
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar"; 

// Define custom fonts using localFont.
const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Path to Geist Sans font file.
  variable: "--font-geist-sans", // CSS variable for font family.
  weight: "100 900", // Font weight range.
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Path to Geist Mono font file.
  variable: "--font-geist-mono", // CSS variable for font family.
  weight: "100 900", // Font weight range.
});

// Metadata for the application.
export const metadata: Metadata = {
  title: "Create Next App", // Title of the application.
  description: "Generated by create next app", // Description of the application.
};

// RootLayout component that renders the application layout.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // JSX to render the HTML structure of the application.
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> {/* Apply font styles and antialiasing */}
        <Navbar /> {/* Render the Navbar component */}
        {children} {/* Render the children components */}
      </body>
    </html>
  );
}