import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-400 p-9 ">   {/*manipulated*/}
        <Link href="/">Home</Link>
        <Link href="/Dashboard" className="p-5">Dashboard</Link>
        <Link href="/blog">Blog</Link>
        
        </header>
        {children}
        <footer className="bg-slate-400 p-9">This is a footer</footer>
      </body>
    </html>
  );
}
